//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Chefao.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_CHEFAO_H)
#define _CHEFAO_H

#include "Inimigo.h"

class Chefao : public Inimigo {
public:
	void executar();
	void ...();
	virtual void = 0 executar();
	virtual void = o danificar(*Jogador p);
	virtual void = 0 salva();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 mover();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 executar();
private:
	int ...;
	short int forca;
};

#endif  //_CHEFAO_H
