//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Chefao.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Chefao.h"

void Chefao::executar() {

}

void Chefao::...() {

}

virtual void = 0 Chefao::executar() {

}

virtual void = o Chefao::danificar(*Jogador p) {

}

virtual void = 0 Chefao::salva() {

}

virtual void = 0 Chefao::executar() {

}

virtual void = 0 Chefao::salvar() {

}

virtual void = 0 Chefao::mover() {

}

virtual void = 0 Chefao::executar() {

}

virtual void = 0 Chefao::salvar() {

}

virtual void = 0 Chefao::executar() {

}

