//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Chefao.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_CHEFAO_H)
#define _CHEFAO_H

#include "Inimigo.h"

class Chefao : public Inimigo {
private:
	//int ...;
	short int forca;
public:
	//void ...();
	void salvar();
	void executar();
	void danificar(Jogador* p);
	void mover();
};

#endif  //_CHEFAO_H
