//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Elemento.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_ELEMENTO_H)
#define _ELEMENTO_H


template <class TE> class Elemento {
public:
	Elemento();
	~Elemento();
	void incluir(*TE p);
	void setProx(*Elemento<TE> pE);
	*Elemento<TE> const getPRoximo();
private:
	*Elemento<TE> pProx;
	*TE pinfo;
};

#endif  //_ELEMENTO_H
