//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Elemento.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Elemento.h"

Elemento::Elemento() {

}

Elemento::~Elemento() {

}

void Elemento::incluir(*TE p) {

}

void Elemento::setProx(*Elemento<TE> pE) {

}

*Elemento<TE> Elemento::const getPRoximo() {

}

