//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Entidade.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_ENTIDADE_H)
#define _ENTIDADE_H

#include "Ente.h"

class Entidade : public Ente {
public:
	Entidade();
	~virtual  Entidade();
	virtual virtual void = 0 executar() = 0;
	virtual virtual void = 0 salvar() = 0;
	void ...();
	virtual void = 0 executar();
protected:
	int x;
	int y;
	int ...;
	ostream buffer;
	void salvarDataBuffer();
};

#endif  //_ENTIDADE_H
