//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Entidade.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Entidade.h"

Entidade::Entidade() {

}

Entidade::~virtual  Entidade() {

}

void Entidade::...() {

}

virtual void = 0 Entidade::executar() {

}

void Entidade::salvarDataBuffer() {

}

