//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Fase Segunda.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_FASE SEGUNDA_H)
#define _FASE SEGUNDA_H

#include "Fase.h"

class Fase Segunda : public Fase {
public:
	void ...();
	virtual void = 0 executar();
protected:
	void criarChefoes();
	void criarObstMedios();
	void criarProjeteis();
	vrtual void = 0 criarInimgos();
	virtual void = 0 criarObstaculo();
private:
	int ...;
	const int maxChefoes;
};

#endif  //_FASE SEGUNDA_H
