//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Fase Primeira.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#ifndef _FASE PRIMEIRA_H
#define _FASE PRIMEIRA_H

#include "Fase.h"

class Fase_Primeira: public Fase {
public:
	//void ...();
	virtual void executar() = 0;
protected:
	void criarInimMedios();
	void criarObstMedios();
	virtual void criarInimgos() = 0;
	virtual void criarObstaculo() = 0;
private:
	//int ...;
	const int maxInimMedios;
};

#endif  //_FASE PRIMEIRA_H
