//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Fase Segunda.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Fase Segunda.h"

void Fase Segunda::...() {

}

virtual void = 0 Fase Segunda::executar() {

}

void Fase Segunda::criarChefoes() {

}

void Fase Segunda::criarObstMedios() {

}

void Fase Segunda::criarProjeteis() {

}

vrtual void = 0 Fase Segunda::criarInimgos() {

}

virtual void = 0 Fase Segunda::criarObstaculo() {

}

