//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Inim_Medio.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Inim_Medio.h"

void Inim_Medio::...() {

}

void Inim_Medio::salvar() {

}

virtual void = 0 Inim_Medio::executar() {

}

virtual void = o Inim_Medio::danificar(*Jogador p) {

}

virtual void = 0 Inim_Medio::salva() {

}

virtual void = 0 Inim_Medio::executar() {

}

virtual void = 0 Inim_Medio::salvar() {

}

virtual void = 0 Inim_Medio::mover() {

}

virtual void = 0 Inim_Medio::executar() {

}

virtual void = 0 Inim_Medio::salvar() {

}

virtual void = 0 Inim_Medio::executar() {

}

