//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Inim_Facil.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Inim_Facil.h"

void Inim_Facil::danificar(*Jogador p) {

}

void Inim_Facil::executar() {

}

void Inim_Facil::...() {

}

virtual void = 0 Inim_Facil::executar() {

}

virtual void = o Inim_Facil::danificar(*Jogador p) {

}

virtual void = 0 Inim_Facil::salva() {

}

virtual void = 0 Inim_Facil::executar() {

}

virtual void = 0 Inim_Facil::salvar() {

}

virtual void = 0 Inim_Facil::mover() {

}

virtual void = 0 Inim_Facil::executar() {

}

virtual void = 0 Inim_Facil::salvar() {

}

virtual void = 0 Inim_Facil::executar() {

}

