//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Inimigo.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_INIMIGO_H)
#define _INIMIGO_H

#include "Personagem.h"

class Inimigo : public Personagem {
public:
	void ...();
	void salvarDataBuffer();
	virtual virtual void = 0 executar() = 0;
	virtual virtual void = o danificar(*Jogador p) = 0;
	virtual virtual void = 0 salva() = 0;
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 mover();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 executar();
protected:
	int nivel_maldade;
	int ...;
};

#endif  //_INIMIGO_H
