//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Inim_Medio.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_INIM_MEDIO_H)
#define _INIM_MEDIO_H

#include "Inimigo.h"

class Inim_Medio : public Inimigo {
public:
	void ...();
	void salvar();
	virtual void = 0 executar();
	virtual void = o danificar(*Jogador p);
	virtual void = 0 salva();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 mover();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 executar();
private:
	int ...;
	int tamanho;
};

#endif  //_INIM_MEDIO_H
