//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Inim_Facil.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_INIM_FACIL_H)
#define _INIM_FACIL_H

#include "Inimigo.h"

class Inim_Facil : public Inimigo {
public:
	void danificar(*Jogador p);
	void executar();
	void ...();
	virtual void = 0 executar();
	virtual void = o danificar(*Jogador p);
	virtual void = 0 salva();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 mover();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 executar();
private:
	int ...;
	float raio;
};

#endif  //_INIM_FACIL_H
