//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Inimigo.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Inimigo.h"

void Inimigo::...() {

}

void Inimigo::salvarDataBuffer() {

}

virtual void = 0 Inimigo::executar() {

}

virtual void = 0 Inimigo::salvar() {

}

virtual void = 0 Inimigo::mover() {

}

virtual void = 0 Inimigo::executar() {

}

virtual void = 0 Inimigo::salvar() {

}

virtual void = 0 Inimigo::executar() {

}

