//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jogador.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_JOGADOR_H)
#define _JOGADOR_H

#include "Personagem.h"

class Jogador : public Personagem {
public:
	Jogador();
	~Jogador();
	void colidir(Inimigo* pIn);
	void executar();
	void salvar();
	void ...();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 mover();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 executar();
protected:
	int pontos;
	int ...;
};

#endif  //_JOGADOR_H
