//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jogador.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Jogador.h"

Jogador::Jogador() {

}

Jogador::~Jogador() {

}

void Jogador::colidir(Inimigo* pIn) {

}

void Jogador::executar() {

}

void Jogador::salvar() {

}

void Jogador::...() {

}

virtual void = 0 Jogador::executar() {

}

virtual void = 0 Jogador::salvar() {

}

virtual void = 0 Jogador::mover() {

}

virtual void = 0 Jogador::executar() {

}

virtual void = 0 Jogador::salvar() {

}

virtual void = 0 Jogador::executar() {

}

