//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Lista.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_LISTA_H)
#define _LISTA_H


template <class TL> class Lista {
public:
	Lista();
	~Lista();
	void incluir(*TL p);
	void limpar();
	void ...();
private:
	*Elemento<TL> pPrimeiro;
	*Elemento<TL> pUltimo;
};

#endif  //_LISTA_H
