//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ListaEntidades.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "ListaEntidades.h"

ListaEntidades::ListaEntidades() {

}

ListaEntidades::~ListaEntidades() {

}

void ListaEntidades::incluir(*Entidade pE) {

}

void ListaEntidades::percorrer() {

}

void ListaEntidades::...() {

}

