//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Lista.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Lista.h"

Lista::Lista() {

}

Lista::~Lista() {

}

void Lista::incluir(*TL p) {

}

void Lista::limpar() {

}

void Lista::...() {

}

