//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Menu.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Menu.h"

Menu::Menu() {

}

Menu::~Menu() {

}

void Menu::executar() {

}

void Menu::...() {

}

virtual void = 0 Menu::executar() {

}

