//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Menu.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_MENU_H)
#define _MENU_H

#include "Ente.h"

class Menu : public Ente {
public:
	Menu();
	~Menu();
	void executar();
	void ...();
	virtual void = 0 executar();
private:
	int ...;
	Jogo* pJog;
};

#endif  //_MENU_H
