//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Obstaculo.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Obstaculo.h"

Obstaculo::Obstaculo() {

}

Obstaculo::~Obstaculo() {

}

void Obstaculo::salvarDataBuffer() {

}

void Obstaculo::...() {

}

virtual void = 0 Obstaculo::executar() {

}

virtual void = 0 Obstaculo::salvar() {

}

virtual void = 0 Obstaculo::executar() {

}

