//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Obst_Medio.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Obst_Medio.h"

void Obst_Medio::...() {

}

void Obst_Medio::executar() {

}

void Obst_Medio::obstaculizar(Jogador* p) {

}

virtual void = 0 Obst_Medio::executar() {

}

virtual void = 0 Obst_Medio::salvar() {

}

virtual void = 0 Obst_Medio::obstaculizar(*Jogador p) {

}

virtual void = 0 Obst_Medio::executar() {

}

virtual void = 0 Obst_Medio::salvar() {

}

virtual void = 0 Obst_Medio::executar() {

}

