//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Obst_Dificil.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Obst_Dificil.h"

void Obst_Dificil::...() {

}

void Obst_Dificil::salvarDataBuffer() {

}

void Obst_Dificil::executar() {

}

void Obst_Dificil::obstaculizar(Jogador* p) {

}

virtual void = 0 Obst_Dificil::executar() {

}

virtual void = 0 Obst_Dificil::salvar() {

}

virtual void = 0 Obst_Dificil::obstaculizar(*Jogador p) {

}

virtual void = 0 Obst_Dificil::executar() {

}

virtual void = 0 Obst_Dificil::salvar() {

}

virtual void = 0 Obst_Dificil::executar() {

}

