//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Obst_Dificil.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_OBST_DIFICIL_H)
#define _OBST_DIFICIL_H

#include "Obstaculo.h"

class Obst_Dificil : public Obstaculo {
public:
	void ...();
	void salvarDataBuffer();
	void executar();
	void obstaculizar(Jogador* p);
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 obstaculizar(*Jogador p);
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 executar();
private:
	int ...;
	short int danosidade;
};

#endif  //_OBST_DIFICIL_H
