//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Obstaculo.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_OBSTACULO_H)
#define _OBSTACULO_H

#include "Entidade.h"

class Obstaculo : public Entidade {
public:
	Obstaculo();
	~Obstaculo();
	void salvarDataBuffer();
	virtual virtual void = 0 executar() = 0;
	virtual virtual void = 0 salvar() = 0;
	virtual virtual void = 0 obstaculizar(*Jogador p) = 0;
	void ...();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 executar();
protected:
	bool danoso;
	int ...;
};

#endif  //_OBSTACULO_H
