//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Obst_Medio.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_OBST_MEDIO_H)
#define _OBST_MEDIO_H

#include "Obstaculo.h"

class Obst_Medio : public Obstaculo {
public:
	void ...();
	void executar();
	void obstaculizar(Jogador* p);
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 obstaculizar(*Jogador p);
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 executar();
private:
	int ...;
	float largura;
};

#endif  //_OBST_MEDIO_H
