//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Personagem.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Personagem.h"

Personagem::Personagem() {

}

Personagem::~Personagem() {

}

void Personagem::salvarDataBuffer() {

}

void Personagem::...() {

}

virtual void = 0 Personagem::executar() {

}

virtual void = 0 Personagem::salvar() {

}

virtual void = 0 Personagem::executar() {

}

