//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Personagem.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_PERSONAGEM_H)
#define _PERSONAGEM_H

#include "Entidade.h"

class Personagem : public Entidade {
public:
	Personagem();
	~Personagem();
	void salvarDataBuffer();
	virtual virtual void = 0 executar() = 0;
	virtual virtual void = 0 salvar() = 0;
	virtual virtual void = 0 mover() = 0;
	void ...();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 executar();
protected:
	int num_vidas;
	int ...;
};

#endif  //_PERSONAGEM_H
