//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Plataforma.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_PLATAFORMA_H)
#define _PLATAFORMA_H

#include "Obstaculo.h"

class Plataforma : public Obstaculo {
public:
	Plataforma();
	~Plataforma();
	void executar();
	void obstaculizar(Jogador* p);
	void ...();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 obstaculizar(*Jogador p);
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 executar();
private:
	int ...;
	int altura;
};

#endif  //_PLATAFORMA_H
