//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Plataforma.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Plataforma.h"

Plataforma::Plataforma() {

}

Plataforma::~Plataforma() {

}

void Plataforma::executar() {

}

void Plataforma::obstaculizar(Jogador* p) {

}

void Plataforma::...() {

}

virtual void = 0 Plataforma::executar() {

}

virtual void = 0 Plataforma::salvar() {

}

virtual void = 0 Plataforma::obstaculizar(*Jogador p) {

}

virtual void = 0 Plataforma::executar() {

}

virtual void = 0 Plataforma::salvar() {

}

virtual void = 0 Plataforma::executar() {

}

