//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Projetil.cpp
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#include "Projetil.h"

Projetil::Projetil() {

}

Projetil::~Projetil() {

}

void Projetil::...() {

}

void Projetil::executar() {

}

void Projetil::salvar() {

}

virtual void = 0 Projetil::executar() {

}

virtual void = 0 Projetil::salvar() {

}

virtual void = 0 Projetil::executar() {

}

