//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Projetil.h
//  @ Date : 08/05/2026
//  @ Author : 
//
//


#if !defined(_PROJETIL_H)
#define _PROJETIL_H

#include "Entidade.h"

class Projetil : public Entidade {
public:
	Projetil();
	~Projetil();
	void ...();
	void executar();
	void salvar();
	virtual void = 0 executar();
	virtual void = 0 salvar();
	virtual void = 0 executar();
protected:
	int . . .;
	bool ativo;
};

#endif  //_PROJETIL_H
